jdbc:
  username: root
  password: 123
  url: jdbc:mysql://localhost:3306/
  database:
    base: rm_data
    ldbc:
      source: movie_q7_1
      target: movie_q7_2
    q2: result_data_2
    q6: result_data_6
lpg:
  url:
    base: /home/graphdata/social_network-csv_basic-longdateformatter-sf1/
rdf:
  url:
    base: /home/graphdata/RDF/mapping_en.ttl
    ldbc: /home/graphdata/RDF/LDBC_RDF.ttl