/* Generated By:JavaCC: Do not edit this line. MathExpressionParserConstants.java */
package com.getl.datalog.math.cc;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MathExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int DIGITS = 2;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int MULTIPLIE = 6;
  /** RegularExpression Id. */
  int DIVIDE = 7;
  /** RegularExpression Id. */
  int OPEN_PAR = 8;
  /** RegularExpression Id. */
  int CLOSE_PAR = 9;
  /** RegularExpression Id. */
  int POW_PAR = 10;
  /** RegularExpression Id. */
  int MIN = 11;
  /** RegularExpression Id. */
  int MAX = 12;
  /** RegularExpression Id. */
  int SUM = 13;
  /** RegularExpression Id. */
  int VAR_NAME = 14;
  /** RegularExpression Id. */
  int COMMA = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<DIGITS>",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"^\"",
    "\"min\"",
    "\"max\"",
    "\"sum\"",
    "<VAR_NAME>",
    "\",\"",
  };

}
